### ISSUE TITLE
Error when using the library

### ISSUE THREAD

**Issue by KirtiSharma28** [AsserData/react-native-universal-pedometer#2]
When I use your library's code I'm getting the following error
undefined is not an object (evaluating '_reactNative.NativeModules.BMDPedometer.BMDPedometer')

Do you know how do I fix this ?

**Comment by Josema** [comment]
Same here, docu does not explain how to react-native link or manual configuration...

**Comment by JWWon** [comment]
Hey guys! Check my forked project. I fix some major bugs and also add typescript support.

https://github.com/JWWon/react-native-universal-pedometer

**Comment by raisiqueira** [comment]
So... this library is not more maintened, please see the @JWWon fork. Thanks. https://github.com/JWWon/react-native-universal-pedometer
