### ISSUE TITLE
Is it possible to keep the pedometer updates running even if the app is closed? If it's possible then how?

### ISSUE THREAD

**Issue by gypsicoder** [AsserData/react-native-universal-pedometer#3]

**Comment by raisiqueira** [comment]
Hi, @gypsicoder it's not possible, but you can use another library to access the steps data (on iOS).

PS.: We dont't more support this library.

**Comment by gypsicoder** [comment]
@raisiqueira  thank you for your quick answer. Can you please suggest how to get the number of steps even if the app is closed? If there is any library please give link. It will be very helpful for me.

**Comment by raisiqueira** [comment]
@gypsicoder you can use the Expo Pedometer API with Bare installation. https://docs.expo.io/versions/v36.0.0/sdk/pedometer/

**Comment by gypsicoder** [comment]
@raisiqueira Thank you for the help. I am really grateful to you.
